### ISSUE TITLE
dealing with level data

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/PCMDIobs-cmor-tables#17]
@durack1 @doutriaux1 If you have a chance sometime in the next few weeks @zyuying has not yet been able to run CMOR with level data, although we do have an example...

**Comment by durack1** [comment]
@zyuying let me know when you're working on this, I'm in this week so could help you get started with the demo

**Comment by zyuying** [comment]
@durack1 @gleckler1 
I upload the runCmor codes from the 3D raw data for ERA-INT, ERA-40, and JRA-25 to my branch "18_yz_testnewbranch". FYI, the pressure dimension in ERA-INT and ERA-40 is from top to surface (not surface to top) and the units is 'hPa' not 'Pa'. It seems these input have a mismatch with table PMPObs_Amon and can't be converted automatically. I made changes to the ERA codes and get them work now. However, there are still error messages from the code for JRA-25. Listed below:

(cmor331) -bash-4.1$ python -i runCmor_JRA25_3D.py
0 vgrdprs
/work/zhang24/anaconda2/envs/cmor331/lib/python2.7/site-packages/cdms2/axis.py:762: UserWarning: genutil module not present, was not able to determine if axis is level based on units
  "genutil module not present, was not able to determine if axis is level based on units")
Traceback (most recent call last):
  File "runCmor_JRA25_3D_orig.py", line 108, in <module>
    cmor.write(varid,values,time_vals=time[:],time_bnds=time_bounds()) ; # Write variable with time axis
TypeError: 'numpy.ndarray' object is not callable

**Comment by taylor13** [comment]
@doutriaux1 Apparently there is a bug in the function cmor_flip_hybrid and in the units conversion since CMOR was unable to handle the input originally provided by Yuying.  According to our documentation, she shouldn't have to reorder things and scale the data before calling CMOR.

Not sure what the other error message is about.

**Comment by durack1** [comment]
@taylor13 this is likely due to `genutil` not being installed, I would recommend that we fold this package into the anaconda distribution by default - @doutriaux1 @mauzey1 comments?

**Comment by taylor13** [comment]
I want CMOR to be independent of as many external packages as possible.  The flipping and units conversion are all done internally by CMOR.   Is there a compelling reason to include genutil?

**Comment by durack1** [comment]
The error above is in the python call to CMOR, so makes me think that the error is before CMOR sees the data

**Comment by doutriaux1** [comment]
@taylor13 I'll look into ithis, but we should clarify if Yuying is using CMOR2 or CMOR3 first.

**Comment by durack1** [comment]
@doutriaux1 `CMOR 3.3.1` (I created the env)

**Comment by taylor13** [comment]
Charles pointed out to me that it's not an error, just a warning.   So, probably should be ignored in this case if the output looks correct.

**Comment by zyuying** [comment]
For example, the error message will show:
C Traceback:
! In function: cmor_treat_axis_values
! called from: cmor_axis
!

!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Error: requested value 15000.000000 for axis plev19 (table: PMPObs_Amon) was not found
!
!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by doutriaux1** [comment]
@zyuying the units convertion should happen automatically within CMOR though. I'll take a lok and see if i can reprodiuce it.

**Comment by taylor13** [comment]
@zyuying It would probably help to know what plev19 values appear as "requested" in PMPObs_Amon.  Also, what values are you passing CMOR when you define the vertical axis (i.e. what pressure levels are being passed by you)?  Can you copy both sets of values to this issue thread?
