### ISSUE TITLE
update catalogue jsons

### ISSUE THREAD

**Issue by gleckler1** [PCMDI/PCMDIobs-cmor-tables#30]
@zyuying @chengzhuzhang just testing here

**Comment by lee1043** [comment]
@gleckler1 Latest catalogue JSONs are needed for the PCMDI Simulation Summary on PCMDI  and CMEC websites. Having JSONs linked from the websites to this repo, rather than have copy of JSONs on repos for both websites, will make websites maintenance easier.

**Comment by gleckler1** [comment]
Working on it now
